from tkinter import *
from tkinter import ttk, messagebox
from googletrans import Translator
from googletrans import LANGUAGES
from playsound import playsound
from deep_translator import GoogleTranslator
from gtts import gTTS
import pyttsx3
import turtle
import 	pygame
import os

root = Tk()
root.title('Japanese Letters')
root.geometry('2000x2000')
root.config(bg="pink")

pygame.mixer.init()

TforE=Label(root, text=" ENGLISH ",background="pink",foreground='#1E90FF',font='tahoma 15 bold')
TforE.grid(row=0, column=0, columnspan=5)
Enter1=Entry(root, background="white", foreground='#1E90FF', font=('arial', 10, "bold"), width=10)
Enter1.grid(row=0, column=3, ipadx=45, ipady=25, columnspan=8, pady=20, padx=50)

Enter2=Label(root, text='Translated Text', background="white", foreground='#1E90FF', font=('arial', 20, "bold"), width=10)
Enter2.grid(row=0, column=11, ipadx=70, ipady=20, columnspan=11, pady=20, padx=50)

def convert_lang():
	text=Enter1.get()
	if(len(text)==0):
		return
	
	convert="ja"
	gt=GoogleTranslator(target=convert)
	ttext=gt.translate(text)
	Enter2.config(text=ttext)
	
	myobj=gTTS(text=ttext,lang='ja',slow=False)
	myobj.save("speak.mpeg")
	playsound('speak.mpeg')
	os.remove('speak.mpeg')
	
translate=Button(root, text="Translate In Japanese",command=convert_lang, background="#1E90FF", foreground="white", font=('arial',10,"bold"))
translate.grid(row=0, column=8, columnspan=8, pady=20, padx=50)


class hiragana:
	def exit(self):
		q = messagebox.askyesno('Exit.','do you want to leave?'.title())
		if q == True:
			root.destroy()
		else:
			pass

	def a(self):
		pygame.mixer.music.load("a.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('あ  ', font=style, align='center')	

		t.up()
		t.home()
		t.goto(-100,0)
		t.down()

		t.right(15)
		t.circle(300,30)

		t.up()
		t.goto(-10,50)
		t.down()

		t.right(120)
		t.circle(400,30)

		t.up()
		t.goto(40,-30)
		t.down()

		t.right(20)
		t.circle(-120,50)
		t.circle(-50,50)
		t.forward(5)
		t.circle(-40,120)	
		t.circle(-80,170)	
		
	def i(self):
		pygame.mixer.music.load("i.mpeg")
		pygame.mixer.music.play(loops=0)		
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('い  ', font=style, align='center')	
		
		t.up()
		t.home()
		t.goto(-100,60)
		t.down()
		t.right(-250)
		t.circle(250,40)
		t.left(-270)
		t.circle(60,50)

		t.up()
		t.goto(10,55)
		t.down()

		t.right(130)
		t.circle(-100,50)
			
	def u(self):
		pygame.mixer.music.load("u.mpeg")
		pygame.mixer.music.play(loops=0)		
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('う  ', font=style, align='center')		

		t.up()
		t.home()
		t.goto(-50,50)
		t.down()

		t.right(15)
		t.forward(60)

		t.up()
		t.goto(-75,0)
		t.down()

		t.left(20)
		t.forward(60)
		t.circle(-50,140)
		t.right(10)
		t.forward(80)

	def e(self):
		pygame.mixer.music.load("e.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('え  ', font=style, align='center')		
		
		t.up()
		t.home()
		t.goto(-50,60)
		t.down()

		t.right(10)
		t.forward(60)

		t.up()
		t.goto(-60,20)
		t.down()

		t.left(15)
		t.forward(80)
		t.right(120)
		t.forward(140)
		t.backward(40)
		t.left(180)
		t.circle(-40,170)
		t.left(10)
		t.circle(20,120)

	def o(self):
		pygame.mixer.music.load("o.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('お  ', font=style, align='center')		

		t.up()
		t.home()
		t.goto(-50,0)
		t.down()

		t.forward(100)

		t.up()
		t.goto(0,50)
		t.down()

		t.right(90)
		t.forward(150)
		t.circle(-20,200)
		t.left(10)
		t.circle(-50,130)
		t.circle(-45,80)

		t.up()
		t.goto(70,5)
		t.down()

		t.left(80)
		t.forward(25)
	
	def ka(self):
		pygame.mixer.music.load("ka.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('か  ', font=style, align='center')		
	
		t.up()
		t.home()
		t.goto(-50,0)
		t.down()

		t.forward(70)
		t.circle(-30,100)
		t.forward(70)

		t.up()
		t.goto(-10,30)
		t.down()
		t.right(5)
		t.forward(120)

		t.up()
		t.goto(60,10)
		t.down()

		t.left(70)
		t.circle(-50,40)

	def ki(self):
		pygame.mixer.music.load("ki.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('き  ', font=style, align='center')

		t.up()
		t.home()
		t.goto(-100,50)
		t.down()
		t.left(10)
		t.forward(100)
		t.up()
		t.goto(-110,0)
		t.down()
		t.forward(130)
		t.up()
		t.goto(-50,80)
		t.down()
		t.right(85)
		t.forward(130)
		t.left(-140)
		t.circle(30,50)
		t.up()
		t.goto(-100,-90)
		t.down()
		t.left(80)
		t.circle(50,80)
		t.forward(50)		
		
	def ku(self):
		pygame.mixer.music.load("ku.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('く  ', font=style, align='center')

		t.up()
		t.home()
		t.goto(-50,50)
		t.down()

		t.right(135)
		t.forward(100)
		#t.backward(100)
		t.left(100)
		t.forward(90)				
		
	def ke(self):
		pygame.mixer.music.load("ke.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('け  ', font=style, align='center')

		t.up()
		t.home()
		t.goto(-50,50)
		t.down()

		t.right(110)
		t.circle(180,40)

		t.up()
		t.goto(20,50)
		t.down()

		t.circle(-180,40)

		t.up()
		t.goto(-10,20)
		t.down()

		t.left(110)
		t.forward(70)

		t.up()
		t.goto(70,190)
		t.down()
		
	def ko(self):
		pygame.mixer.music.load("ko.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('こ  ', font=style, align='center')	

		t.up()
		t.home()
		t.goto(-30,0)
		t.down()

		t.left(15)
		t.circle(-150,40)
		t.right(150)
		t.circle(20,40)

		t.up()
		t.goto(-30,-60)
		t.down()

		t.circle(20,80)
		t.left(30)
		t.circle(150,40)
			
	def sa(self):
		pygame.mixer.music.load("sa.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('さ  ', font=style, align='center')

		t.up()
		t.home()
		t.goto(-50,0)
		t.down()

		t.left(10)
		t.forward(100)

		t.up()
		t.goto(-10,50)
		t.down()

		t.right(85)
		t.forward(120)

		t.left(-140)
		t.circle(50,50)

		t.up()
		t.goto(-50,-100)
		t.down()

		t.left(80)
		t.circle(50,80)

		t.forward(40)		
		
	def shi(self):
		pygame.mixer.music.load("shi.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('し  ', font=style, align='center')	

		t.up()
		t.home()
		t.goto(-100,0)
		t.down()

		t.right(110)
		t.circle(200,30)
		t.circle(30,100)
		t.left(3)
		t.forward(30)
		
	def su(self):
		pygame.mixer.music.load("su.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('す  ', font=style, align='center')	

		t.up()
		t.home()
		t.goto(0,50)
		t.down()
		
		t.right(90)
		t.forward(80) 

		t.circle(-15)
		t.forward(40)
		t.circle(-50,40)

		t.up()
		t.goto(-40,20)
		t.down()

		t.right(230)
		t.forward(80)	
	
	def se(self):
		pygame.mixer.music.load("se.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('せ  ', font=style, align='center')	

		t.up()
		t.home()
		t.goto(-50,20)
		t.down()

		t.forward(110)

		t.up()
		t.goto(-20,50)
		t.down()

		t.right(90)
		t.forward(80)
		t.circle(20,90)
		t.forward(20)

		t.up()
		t.goto(30,50)
		t.down()

		t.right(90)
		t.forward(60)
		t.right(85)
		t.circle(10,20)
		t.forward(10)
		
	def so(self):
		pygame.mixer.music.load("so.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('そ  ', font=style, align='center')	

		t.up()
		t.home()
		t.goto(-50,10)
		t.down()

		t.forward(120)
		t.right(140)
		t.forward(150)
		t.left(140)
		t.forward(120)
		t.right(190)
		t.circle(50,200)	
		
	def ta(self):
		pygame.mixer.music.load("ta.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('た  ', font=style, align='center')

		t.up()
		t.home()
		t.goto(-50,70)
		t.down()

		t.right(110)
		t.circle(220,40)

		t.up()
		t.goto(-100,30)
		t.down()

		t.left(70)
		t.forward(90)

		t.up()
		t.goto(-10,00)
		t.down()

		t.left(20)
		t.circle(-150,30)

		t.up()
		t.goto(-10,-40)
		t.down()

		t.circle(150,30)
		
	def chi(self):
		pygame.mixer.music.load("chi.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('ち  ', font=style, align='center')	

		t.up()
		t.home()
		t.goto(-70,20)
		t.down()

		t.forward(100)

		t.up()
		t.goto(0,50)
		t.down()

		t.right(120)
		t.forward(100)
		t.left(140)
		t.circle(-50,200)
		t.forward(50)
			
	def tsu(self):
		pygame.mixer.music.load("tsu.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('つ  ', font=style, align='center')	

		t.up()
		t.home()
		t.goto(-50,0)
		t.down()

		t.left(30)
		t.circle(-200,40)
		t.right(5)
		t.circle(-50,150)
		t.forward(50)
				
	def te(self):
		pygame.mixer.music.load("te.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('て  ', font=style, align='center')	

		t.up()
		t.home()
		t.goto(-100,0)
		t.down()

		t.forward(90)
		t.right(180)
		t.circle(100,30)
		t.circle(40,140)
		t.forward(20)
			
	def to(self):
		pygame.mixer.music.load("to.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('と  ', font=style, align='center')	

		t.up()
		t.home()
		t.goto(-30,20)
		t.down()

		t.right(55)
		t.forward(55)

		t.up()
		t.goto(50,0)
		t.down()

		t.right(95)
		t.forward(90)
		t.circle(50,140)
		t.left(10)
		t.forward(50)	
		
	def na(self):
		pygame.mixer.music.load("na.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('な  ', font=style, align='center')	

		t.up()
		t.home()
		t.goto(-50,20)
		t.down()

		t.right(110)
		t.circle(250,40)

		t.up()
		t.goto(-100,-20)
		t.down()

		t.left(70)
		t.forward(100)

		t.up()
		t.goto(30,-25)
		t.down()

		t.right(30)
		t.circle(-100,20)

		t.up()
		t.goto(30,-50)
		t.down()

		t.right(70)
		t.circle(100,40)
		t.circle(-20,290)
		t.left(20)
		t.circle(-80,55)	
				
	def ni(self):
		pygame.mixer.music.load("ni.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('に  ', font=style, align='center')		

		t.up()
		t.home()
		t.goto(-20,20)
		t.down()

		t.right(110)
		t.circle(250,35)
		t.left(150)
		t.circle(-30,30)

		t.up()
		t.goto(0,-40)
		t.down()

		t.left(-30)
		t.circle(-150,30)

		t.up()
		t.goto(-20,-90)
		t.down()
		t.right(50)
		t.circle(30,70)
		t.forward(55)
		
	def nu(self):
		pygame.mixer.music.load("nu.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('ぬ  ', font=style, align='center')	

		t.up()
		t.home()
		t.goto(-20,40)
		t.down()

		t.right(90)
		t.circle(300,25)

		t.up()
		t.goto(20,30)
		t.down()

		t.left(-10)
		t.circle(-120,50)
		t.circle(-20,100)
		t.right(10)
		t.circle(-40,110)
		t.left(5)
		t.forward(5)
		t.forward(10)
		t.circle(-70,120)
		t.circle(-15,300)
		t.forward(40)
				
	def ne(self):
		pygame.mixer.music.load("ne.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('ね  ', font=style, align='center')	

		t.up()
		t.home()
		t.goto(0,50)
		t.down()

		t.right(110)
		t.circle(250,35)
		t.left(75)

		t.up()
		t.goto(-90,20)
		t.down()

		t.forward(100)
		t.right(140)
		t.forward(80)
		t.left(180)
		t.circle(-10,20)
		t.left(25)
		t.circle(-90,110)
		#t.forward(20)
		t.circle(-40,100)
		t.circle(-15,220)
		t.forward(60)
		
	def no(self):
		pygame.mixer.music.load("no.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('の  ', font=style, align='center')

		t.up()
		t.home()
		t.goto(-50,0)
		t.down()
		t.right(100)

		t.forward(30)
		t.left(10)
		t.circle(-80,50)
		t.backward(5)
		t.left(10)
		t.circle(-25,95)
		t.right(25)
		t.circle(-80,210)
		t.circle(-50,70)
				
	def ha(self):
		pygame.mixer.music.load("ha.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('は  ', font=style, align='center')	

		t.up()
		t.home()
		t.goto(-50,0)
		t.down()

		t.right(110)
		t.circle(200,35)
		t.left(150)
		t.circle(-50,30)

		t.up()
		t.goto(-15,-30)
		t.down()

		t.left(-45)
		t.forward(80)
		t.up()
		t.goto(20,0)
		t.down()

		t.right(90)
		t.forward(100)
		t.circle(-15,270)
		t.circle(-70,50)
				
	def hi(self):
		pygame.mixer.music.load("hi.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('ひ  ', font=style, align='center')	

		t.up()
		t.home()
		t.goto(-100,20)
		t.down()

		t.left(10)
		t.forward(70)
		t.right(135)
		t.circle(120,48)
		t.circle(60,130)
		t.right(-10)
		t.circle(100,60)
		t.right(160)
		t.forward(60)		
		
	def fu(self):
		pygame.mixer.music.load("fu.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('ふ  ', font=style, align='center')	


		t.up()
		t.home()
		t.goto(-30,40)
		t.down()

		t.right(20)
		t.circle(-150,15)
		t.up()
		t.goto(-20,0)
		t.down()
		t.right(10)
		t.circle(-100,50)
		t.circle(-30,120)
		t.up()
		t.goto(-40,-50)
		t.down()
		t.left(100)
		t.forward(40)
		t.up()
		t.goto(30,-30)
		t.down()
		t.left(50)
		t.forward(40)
					
	def he(self):
		pygame.mixer.music.load("he.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('へ  ', font=style, align='center')

		t.up()
		t.home()
		t.goto(-100,-50)
		t.down()
		t.left(50)
		t.forward(100)
		t.right(90)
		t.forward(140)
		
	def ho(self):
		pygame.mixer.music.load("ho.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('ほ  ', font=style, align='center')	

		t.up()
		t.home()
		t.goto(-100,10)
		t.down()

		t.right(110)
		t.circle(200,35)
		t.left(150)
		t.circle(-50,30)

		t.up()
		t.goto(-60,0)
		t.down()

		t.left(-45)
		t.forward(80)

		t.up()
		t.goto(-60,-30)
		t.down()
		t.forward(80)

		t.up()
		t.goto(-20,0)
		t.down()

		t.right(90)
		t.forward(100)
		t.circle(-15,270)
		t.circle(-70,50)	
		
	def ma(self):
		pygame.mixer.music.load("ma.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('ま  ', font=style, align='center')		

		t.up()
		t.home()
		t.goto(-100,20)
		t.down()

		t.forward(100)

		t.up()
		t.goto(-90,-20)
		t.down()
		t.forward(80)

		t.up()
		t.goto(-50,50)
		t.down()

		t.right(90)
		t.forward(150)
		t.circle(-20,270)
		t.circle(-100,50)
		
	def mi(self):
		pygame.mixer.music.load("mi.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('み  ', font=style, align='center')		

		t.up()
		t.home()
		t.goto(-100,0)
		t.down()

		t.forward(60)
		t.right(115)
		t.forward(100)
		t.circle(-30,80)
		t.right(50)
		t.circle(-30,105)
		t.left(10)
		t.circle(-100,70)

		t.up()
		t.goto(0,-30)
		t.down()
		t.right(40)
		t.circle(-150,45)
				
	def mu(self):
		pygame.mixer.music.load("mu.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('む  ', font=style, align='center')	

		t.up()
		t.home()
		t.goto(-100,-30)
		t.down()

		#t.right(230)
		t.forward(90)

		t.up()
		t.goto(-50,0)
		t.down()
		
		t.right(90)
		t.forward(90) 

		t.circle(-20)
		t.forward(40)
		t.circle(20,170)
		t.forward(20)

		t.up()
		t.goto(10,-30)
		t.down()
		t.right(120)
		t.forward(35)	
				
	def me(self):
		pygame.mixer.music.load("me.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('め  ', font=style, align='center')		

		t.up()
		t.home()
		t.goto(-50,0)
		t.down()

		t.right(90)
		t.circle(250,25)

		t.up()
		t.goto(0,0)
		t.down()

		t.left(-10)
		t.circle(-100,50)
		t.circle(-30,100)
		t.right(10)
		t.circle(-35,110)
		t.left(5)
		t.forward(10)
		t.forward(20)
		t.circle(-50,170)
		
	def mo(self):
		pygame.mixer.music.load("mo.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('も  ', font=style, align='center')	

		t.up()
		t.home()
		t.goto(-50,0)
		t.down()

		t.right(5)
		t.circle(240,20)

		t.up()
		t.goto(-50,-40)
		t.down()
		t.right(20)
		t.circle(240,20)

		t.up()
		t.goto(0,30)
		t.down()

		t.right(120)
		t.circle(300,25)
		t.circle(40,140)
			
	def ya(self):
		pygame.mixer.music.load("ya.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('や  ', font=style, align='center')	

		t.up()
		t.home()
		t.goto(-100,-50)
		t.down()

		t.left(30)
		t.circle(-200,40)
		t.right(5)
		t.circle(-30,150)
		t.up()
		t.goto(-90,0)
		t.down()
		t.left(100)
		t.forward(90)
		t.up()
		t.goto(0,0)
		t.down()
		t.left(45)
		t.forward(30)
		
	def yu(self):
		pygame.mixer.music.load("yu.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('ゆ  ', font=style, align='center')		

		t.up()
		t.home()
		t.goto(-100,0)
		t.down()

		t.right(100)
		t.forward(100)
		t.backward(40)
		t.left(150)
		t.circle(-100,20)
		t.circle(-70,70)
		t.right(10)
		t.circle(-50,50)
		t.circle(-70,75)
		t.forward(30)
		t.up()
		t.goto(-50,-10)
		t.down()
		t.left(90)
		t.circle(-300,30)
		
	def yo(self):
		pygame.mixer.music.load("yo.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('よ  ', font=style, align='center')	

		t.up()
		t.home()
		t.goto(0,-40)
		t.down()

		t.forward(60)
		t.up()
		t.goto(0,10)
		t.down()

		t.right(90)
		t.forward(150)
		t.circle(-20,270)
		t.circle(-100,50)	
		
	def ra(self):
		pygame.mixer.music.load("ra.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('ら  ', font=style, align='center')		

		t.up()
		t.home()
		t.goto(-100,50)
		t.down()

		t.right(95)
		t.forward(80)
		t.left(120)
		t.circle(-100,20)
		t.circle(-70,70)
		t.right(10)
		t.circle(-50,50)
		t.circle(-70,75)
		t.forward(40)
		t.up()
		t.goto(-85,80)
		t.down()
		t.right(170)
		t.forward(70)
		
	def ri(self):
		pygame.mixer.music.load("ri.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('り  ', font=style, align='center')		

		t.up()
		t.home()
		t.goto(-50,0)
		t.down()

		t.right(100)
		t.circle(250,18)
		t.left(150)
		t.circle(-50,30)

		t.up()
		t.goto(30,0)
		t.down()
		t.right(110)
		t.circle(-100,20)
		t.circle(-200,40)
		
	def ru(self):
		pygame.mixer.music.load("ru.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('る  ', font=style, align='center')

		t.up()
		t.home()
		t.goto(-100,50)
		t.down()

		t.forward(100)
		t.right(140)
		t.forward(150)
		t.left(180)
		t.circle(-100,20)
		t.left(10)
		t.circle(-70,230)
		t.circle(-20,300)
		t.forward(10)
			
	def re(self):
		pygame.mixer.music.load("re.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('れ  ', font=style, align='center')		

		t.up()
		t.home()
		t.goto(-50,30)
		t.down()

		t.right(110)
		t.circle(230,27)
		t.left(85)

		t.up()
		t.goto(-100,10)
		t.down()

		t.forward(50)
		t.right(110)
		t.forward(90)
		t.left(180)
		t.circle(-80,30)
		t.circle(-30,120)
		t.forward(10)
		t.circle(10,200)
		
	def ro(self):
		pygame.mixer.music.load("ro.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('ろ  ', font=style, align='center')

		t.up()
		t.home()
		t.goto(-100,50)
		t.down()

		t.forward(120)
		t.right(140)
		t.forward(150)
		t.left(180)
		t.circle(-110,20)
		t.left(10)
		t.circle(-80,220)
					
	def wa(self):
		pygame.mixer.music.load("wa.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('わ  ', font=style, align='center')		

		t.up()
		t.home()
		t.goto(-50,30)
		t.down()

		t.right(110)
		t.circle(300,27)
		t.left(75)

		t.up()
		t.goto(-100,20)
		t.down()

		t.forward(50)
		t.right(100)
		t.forward(110)
		t.left(180)
		t.circle(-100,40)
		t.circle(-70,60)
		t.circle(-50,150)
		
	def wo(self):
		pygame.mixer.music.load("wo (1).mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('を  ', font=style, align='center')	

		t.up()
		t.home()
		t.goto(-100,20)
		t.down()
		t.forward(100)

		t.up()
		t.goto(-50,50)
		t.down()

		t.right(100)
		t.forward(120)
		t.backward(20)
		t.left(180)
		t.circle(-35,170)
		t.forward(45)

		t.up()
		t.goto(50,-40)
		t.down()

		t.right(70)
		t.forward(80)
		t.circle(40,140)
		t.forward(40)	
		
	def n(self):
		pygame.mixer.music.load("n.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('ん  ', font=style, align='center')	

		t.up()
		t.home()
		t.goto(-50,50)
		t.down()

		t.right(100)
		t.forward(130)
		t.backward(20)
		t.left(180)
		t.circle(-40,170)
		t.forward(20)
		t.left(10)
		t.circle(15,160)	

		
#additional sound		
	def ga(self):
		pygame.mixer.music.load("ga.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('が ', font=style, align='center')	

		t.up()
		t.home()
		t.goto(-50,0)
		t.down()

		t.forward(70)
		t.circle(-30,100)
		t.forward(70)

		t.up()
		t.goto(-10,30)
		t.down()
		t.right(5)
		t.forward(120)

		t.up()
		t.goto(60,10)
		t.down()

		t.left(70)
		t.circle(-50,40)

		t.up()
		t.home()
		t.goto(70,30)
		t.down()
		t.right(30)
		t.forward(30)
		t.up()
		t.goto(80,40)
		t.down()
		t.forward(30)

	def gi(self):
		pygame.mixer.music.load("gi.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('ぎ  ', font=style, align='center')		

		t.up()
		t.home()
		t.goto(-100,50)
		t.down()
		t.left(10)
		t.forward(100)
		t.up()
		t.goto(-110,0)
		t.down()
		t.forward(130)
		t.up()
		t.goto(-50,80)
		t.down()
		t.right(85)
		t.forward(130)
		t.left(-140)
		t.circle(30,50)
		t.up()
		t.goto(-100,-90)
		t.down()
		t.left(80)
		t.circle(50,80)
		t.forward(50)	

		t.up()
		t.home()
		t.goto(0,100)
		t.down()
		t.right(30)
		t.forward(30)
		t.up()
		t.goto(10,110)
		t.down()
		t.forward(30)

	def gu(self):
		pygame.mixer.music.load("gu.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('ぐ  ', font=style, align='center')	

		t.up()
		t.home()
		t.goto(-50,50)
		t.down()

		t.right(135)
		t.forward(100)
		#t.backward(100)
		t.left(100)
		t.forward(90)

		t.up()
		t.home()
		t.goto(-40,40)
		t.down()
		t.right(30)
		t.forward(30)
		t.up()
		t.goto(-30,50)
		t.down()
		t.forward(30)
	
	def ge(self):
		pygame.mixer.music.load("ge.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('げ  ', font=style, align='center')

		t.up()
		t.home()
		t.goto(-50,50)
		t.down()

		t.right(110)
		t.circle(180,40)

		t.up()
		t.goto(20,50)
		t.down()

		t.circle(-180,40)

		t.up()
		t.goto(-10,20)
		t.down()

		t.left(110)
		t.forward(70)

		t.up()
		t.home()
		t.goto(40,40)
		t.down()
		t.right(30)
		t.forward(30)
		t.up()
		t.goto(50,50)
		t.down()
		t.forward(30)	
		
	def go(self):
		pygame.mixer.music.load("go.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('ご  ', font=style, align='center')		

		t.up()
		t.home()
		t.goto(-30,0)
		t.down()

		t.left(15)
		t.circle(-150,40)
		t.right(150)
		t.circle(20,40)

		t.up()
		t.goto(-30,-60)
		t.down()

		t.circle(20,80)
		t.left(30)
		t.circle(150,40)

		t.up()
		t.home()
		t.goto(70,0)
		t.down()
		t.right(30)
		t.forward(30)
		t.up()
		t.goto(80,10)
		t.down()
		t.forward(30)

	def za(self):
		pygame.mixer.music.load("za.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('ざ  ', font=style, align='center')

		t.up()
		t.home()
		t.goto(-50,0)
		t.down()

		t.left(10)
		t.forward(100)

		t.up()
		t.goto(-10,50)
		t.down()

		t.right(85)
		t.forward(120)

		t.left(-140)
		t.circle(50,50)

		t.up()
		t.goto(-50,-100)
		t.down()

		t.left(80)
		t.circle(50,80)

		t.forward(40)

		t.up()
		t.home()
		t.goto(50,40)
		t.down()
		t.right(30)
		t.forward(30)
		t.up()
		t.goto(60,50)
		t.down()
		t.forward(30)	
		
	def ji_zi(self):
		pygame.mixer.music.load("ji.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('じ  ', font=style, align='center')	

		t.up()
		t.home()
		t.goto(-100,0)
		t.down()

		t.right(110)
		t.circle(200,30)
		t.circle(30,100)
		t.left(3)
		t.forward(30)

		t.up()
		t.home()
		t.goto(-80,-10)
		t.down()
		t.right(30)
		t.forward(30)
		t.up()
		t.goto(-70,00)
		t.down()
		t.forward(30)
		
	def zu_zu(self):
		pygame.mixer.music.load("zu.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('ず  ', font=style, align='center')		

		t.up()
		t.home()
		t.goto(0,50)
		t.down()
		
		t.right(90)
		t.forward(80) 

		t.circle(-15)
		t.forward(40)
		t.circle(-50,40)

		t.up()
		t.goto(-40,20)
		t.down()

		t.right(230)
		t.forward(80)	

		t.up()
		t.home()
		t.goto(20,40)
		t.down()
		t.right(30)
		t.forward(30)
		t.up()
		t.goto(30,50)
		t.down()
		t.forward(30)

	def ze(self):
		pygame.mixer.music.load("ze.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('ぜ  ', font=style, align='center')		
	
		t.up()
		t.home()
		t.goto(-50,20)
		t.down()

		t.forward(110)

		t.up()
		t.goto(-20,50)
		t.down()

		t.right(90)
		t.forward(80)
		t.circle(20,90)
		t.forward(20)

		t.up()
		t.goto(30,50)
		t.down()

		t.right(90)
		t.forward(60)
		t.right(85)
		t.circle(10,20)
		t.forward(10)

		t.up()
		t.home()
		t.goto(40,50)
		t.down()
		t.right(30)
		t.forward(30)
		t.up()
		t.goto(50,60)
		t.down()
		t.forward(30)

	def zo(self):
		pygame.mixer.music.load("zo.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('ぞ  ', font=style, align='center')		

		t.up()
		t.home()
		t.goto(-50,10)
		t.down()

		t.forward(120)
		t.right(140)
		t.forward(150)
		t.left(140)
		t.forward(120)
		t.right(190)
		t.circle(50,200)

		t.up()
		t.home()
		t.goto(80,10)
		t.down()
		t.right(30)
		t.forward(30)
		t.up()
		t.goto(90,20)
		t.down()
		t.forward(30)

	def da(self):
		pygame.mixer.music.load("da.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('だ  ', font=style, align='center')	

		t.up()
		t.home()
		t.goto(-50,70)
		t.down()

		t.right(110)
		t.circle(220,40)

		t.up()
		t.goto(-100,30)
		t.down()

		t.left(70)
		t.forward(90)

		t.up()
		t.goto(-10,00)
		t.down()

		t.left(20)
		t.circle(-150,30)

		t.up()
		t.goto(-10,-40)
		t.down()

		t.circle(150,30)

		t.up()
		t.home()
		t.goto(-00,40)
		t.down()
		t.right(30)
		t.forward(30)
		t.up()
		t.goto(10,50)
		t.down()
		t.forward(30)
		
	def ji(self):
		pygame.mixer.music.load("zi.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('ぢ  ', font=style, align='center')	

		t.up()
		t.home()
		t.goto(-70,20)
		t.down()

		t.forward(100)

		t.up()
		t.goto(0,50)
		t.down()

		t.right(120)
		t.forward(100)
		t.left(140)
		t.circle(-50,200)
		t.forward(50)

		t.up()
		t.home()
		t.goto(40,30)
		t.down()
		t.right(30)
		t.forward(30)
		t.up()
		t.goto(50,40)
		t.down()
		t.forward(30)

	def zu(self):
		pygame.mixer.music.load("zu.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('づ  ', font=style, align='center')		

		t.up()
		t.home()
		t.goto(-100,-30)
		t.down()

		t.left(30)
		t.circle(-200,40)
		t.right(5)
		t.circle(-50,150)
		t.forward(50)

		t.up()
		t.home()
		t.goto(50,20)
		t.down()
		t.right(30)
		t.forward(30)
		t.up()
		t.goto(60,30)
		t.down()
		t.forward(30)

	def de(self):
		pygame.mixer.music.load("de.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('で  ', font=style, align='center')		

		t.up()
		t.home()
		t.goto(-100,0)
		t.down()

		t.forward(90)
		t.right(180)
		t.circle(100,30)
		t.circle(40,140)
		t.forward(20)

		t.up()
		t.home()
		t.goto(-40,-20)
		t.down()
		t.right(30)
		t.forward(25)
		t.up()
		t.goto(-30,-10)
		t.down()
		t.forward(25)

	def do(self):
		pygame.mixer.music.load("do.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('ど  ', font=style, align='center')						

		t.up()
		t.home()
		t.goto(-30,20)
		t.down()

		t.right(55)
		t.forward(55)

		t.up()
		t.goto(50,0)
		t.down()

		t.right(95)
		t.forward(90)
		t.circle(50,140)
		t.left(10)
		t.forward(50)	
		
		t.up()
		t.home()
		t.goto(40,30)
		t.down()
		t.right(30)
		t.forward(25)
		t.up()
		t.goto(50,40)
		t.down()
		t.forward(25)

	def ba(self):
		pygame.mixer.music.load("ba.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('ば  ', font=style, align='center')	
		
		t.up()
		t.home()
		t.goto(-50,0)
		t.down()

		t.right(110)
		t.circle(200,35)
		t.left(150)
		t.circle(-50,30)

		t.up()
		t.goto(-15,-30)
		t.down()

		t.left(-45)
		t.forward(80)
		t.up()
		t.goto(20,0)
		t.down()

		t.right(90)
		t.forward(100)
		t.circle(-15,270)
		t.circle(-70,50)

		t.up()
		t.home()
		t.goto(50,0)
		t.down()
		t.right(30)
		t.forward(25)
		t.up()
		t.goto(60,10)
		t.down()
		t.forward(25)

	def bi(self):
		pygame.mixer.music.load("bi.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('び  ', font=style, align='center')	
		
		
		t.up()
		t.home()
		t.goto(-100,20)
		t.down()

		t.left(10)
		t.forward(70)
		t.right(135)
		t.circle(120,48)
		t.circle(60,130)
		t.right(-10)
		t.circle(100,60)
		t.right(160)
		t.forward(60)		

		t.up()
		t.home()
		t.goto(50,40)
		t.down()
		t.right(30)
		t.forward(25)
		t.up()
		t.goto(60,50)
		t.down()
		t.forward(25)

	def bu(self):
		pygame.mixer.music.load("bu.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('ぶ  ', font=style, align='center')		
		
		t.up()
		t.home()
		t.goto(-30,40)
		t.down()

		t.right(20)
		t.circle(-150,15)
		t.up()
		t.goto(-20,0)
		t.down()
		t.right(10)
		t.circle(-100,50)
		t.circle(-30,120)
		t.up()
		t.goto(-40,-50)
		t.down()
		t.left(100)
		t.forward(40)
		t.up()
		t.goto(30,-30)
		t.down()
		t.left(50)
		t.forward(40)

		t.up()
		t.home()
		t.goto(20,40)
		t.down()
		t.right(30)
		t.forward(25)
		t.up()
		t.goto(30,50)
		t.down()
		t.forward(25)
					
	def be(self):
		pygame.mixer.music.load("be.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('べ  ', font=style, align='center')		
		
		t.up()
		t.home()
		t.goto(-100,-50)
		t.down()
		t.left(50)
		t.forward(100)
		t.right(90)
		t.forward(140)

		t.up()
		t.home()
		t.goto(0,25)
		t.down()
		t.right(30)
		t.forward(25)
		t.up()
		t.goto(10,35)
		t.down()
		t.forward(25)

	def bo(self):
		pygame.mixer.music.load("bo.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('ぼ  ', font=style, align='center')		

		t.up()
		t.home()
		t.goto(-100,10)
		t.down()

		t.right(110)
		t.circle(200,35)
		t.left(150)
		t.circle(-50,30)

		t.up()
		t.goto(-60,0)
		t.down()

		t.left(-45)
		t.forward(80)

		t.up()
		t.goto(-60,-30)
		t.down()
		t.forward(80)

		t.up()
		t.goto(-20,0)
		t.down()

		t.right(90)
		t.forward(100)
		t.circle(-15,270)
		t.circle(-70,50)

		t.up()
		t.home()
		t.goto(20,10)
		t.down()
		t.right(30)
		t.forward(25)
		t.up()
		t.goto(30,20)
		t.down()
		t.forward(25)

	def pa(self):
		pygame.mixer.music.load("pa.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('ぱ  ', font=style, align='center')	
		
		t.up()
		t.home()
		t.goto(-50,0)
		t.down()

		t.right(110)
		t.circle(200,35)
		t.left(150)
		t.circle(-50,30)

		t.up()
		t.goto(-15,-30)
		t.down()

		t.left(-45)
		t.forward(80)
		t.up()
		t.goto(20,0)
		t.down()

		t.right(90)
		t.forward(100)
		t.circle(-15,270)
		t.circle(-70,50)

		t.up()
		t.goto(40,0)
		t.down()

		t.left(10)
		t.pensize(5)
		t.circle(15)
		t.pensize(5)

	def pi(self):
		pygame.mixer.music.load("pi.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('ぴ  ', font=style, align='center')	
		
		t.up()
		t.home()
		t.goto(-100,20)
		t.down()

		t.left(10)
		t.forward(70)
		t.right(135)
		t.circle(120,48)
		t.circle(60,130)
		t.right(-10)
		t.circle(100,60)
		t.right(160)
		t.forward(60)

		t.up()
		t.goto(60,30)
		t.down()

		t.left(10)
		t.pensize(5)
		t.circle(15)
		t.pensize(5)		

	def pu(self):
		pygame.mixer.music.load("pu.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('ぷ  ', font=style, align='center')		
		
		t.up()
		t.home()
		t.goto(-30,40)
		t.down()

		t.right(20)
		t.circle(-150,15)
		t.up()
		t.goto(-20,0)
		t.down()
		t.right(10)
		t.circle(-100,50)
		t.circle(-30,120)
		t.up()
		t.goto(-40,-50)
		t.down()
		t.left(100)
		t.forward(40)
		t.up()
		t.goto(30,-30)
		t.down()
		t.left(50)
		t.forward(40)

		t.up()
		t.goto(20,30)
		t.down()

		t.left(10)
		t.pensize(5)
		t.circle(15)
		t.pensize(5)
					
	def pe(self):
		pygame.mixer.music.load("pe.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('ぺ  ', font=style, align='center')		
		
		t.up()
		t.home()
		t.goto(-100,-50)
		t.down()
		t.left(50)
		t.forward(100)
		t.right(90)
		t.forward(140)

		t.up()
		t.goto(20,30)
		t.down()

		t.left(10)
		t.pensize(5)
		t.circle(15)
		t.pensize(5)

	def po(self):
		pygame.mixer.music.load("po.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('ぽ   ', font=style, align='center')		

		t.up()
		t.home()
		t.goto(-100,10)
		t.down()

		t.right(110)
		t.circle(200,35)
		t.left(150)
		t.circle(-50,30)

		t.up()
		t.goto(-60,0)
		t.down()

		t.left(-45)
		t.forward(80)

		t.up()
		t.goto(-60,-30)
		t.down()
		t.forward(80)

		t.up()
		t.goto(-20,0)
		t.down()

		t.right(90)
		t.forward(100)
		t.circle(-15,270)
		t.circle(-70,50)

		t.up()
		t.goto(40,10)
		t.down()

		t.left(10)
		t.pensize(5)
		t.circle(15)
		t.pensize(10)

	def kya(self):
		pygame.mixer.music.load("kya.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('きゃ  ', font=style, align='center')		
		
		t.up()
		t.home()
		t.goto(-200,50)
		t.down()
		t.left(10)
		t.forward(100)
		t.up()
		t.goto(-210,0)
		t.down()
		t.forward(130)
		t.up()
		t.goto(-150,80)
		t.down()
		t.right(85)
		t.forward(130)
		t.left(-140)
		t.circle(30,50)
		t.up()
		t.goto(-200,-90)
		t.down()
		t.left(80)
		t.circle(50,80)
		t.forward(50)	

		t.up()
		t.home()
		t.goto(-80,-60)
		t.down()

		t.left(30)
		t.circle(-100,40)
		t.right(5)
		t.circle(-15,150)
		t.up()
		t.goto(-70,-30)
		t.down()
		t.left(100)
		t.forward(60)
		t.up()
		t.goto(-20,-20)
		t.down()
		t.left(45)
		t.forward(20)

	def kyu(self):
		pygame.mixer.music.load("kyu.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('きゅ  ', font=style, align='center')		
		
		t.up()
		t.home()
		t.goto(-200,50)
		t.down()
		t.left(10)
		t.forward(100)
		t.up()
		t.goto(-210,0)
		t.down()
		t.forward(130)
		t.up()
		t.goto(-150,80)
		t.down()
		t.right(85)
		t.forward(130)
		t.left(-140)
		t.circle(30,50)
		t.up()
		t.goto(-200,-90)
		t.down()
		t.left(80)
		t.circle(50,80)
		t.forward(50)	

		t.up()
		t.home()
		t.goto(0,-50)
		t.down()

		t.right(100)
		t.forward(60)
		t.backward(20)
		t.left(150)
		t.circle(-60,20)
		t.circle(-40,70)
		t.right(10)
		t.circle(-20,50)
		t.circle(-40,75)
		t.forward(20)
		t.up()
		t.goto(30,-60)
		t.down()
		t.left(90)
		t.circle(-170,30)
			
	def kyo(self):
		pygame.mixer.music.load("kyo.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('きょ  ', font=style, align='center')	
	
		t.up()
		t.home()
		t.goto(-200,50)
		t.down()
		t.left(10)
		t.forward(100)
		t.up()
		t.goto(-210,0)
		t.down()
		t.forward(130)
		t.up()
		t.goto(-150,80)
		t.down()
		t.right(85)
		t.forward(130)
		t.left(-140)
		t.circle(30,50)
		t.up()
		t.goto(-200,-90)
		t.down()
		t.left(80)
		t.circle(50,80)
		t.forward(50)	

		t.up()
		t.home()
		t.goto(0,-50)
		t.down()

		t.forward(30)
		t.up()
		t.goto(0,-20)
		t.down()

		t.right(90)
		t.forward(90)
		t.circle(-15,270)
		t.circle(-70,50)	
	
	def gya(self):
		pygame.mixer.music.load("gya.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier',40, 'italic')
		t.write('ぎゃ  ', font=style, align='center')		

		t.up()
		t.home()
		t.goto(-200,50)
		t.down()
		t.left(10)
		t.forward(100)
		t.up()
		t.goto(-210,0)
		t.down()
		t.forward(130)
		t.up()
		t.goto(-150,80)
		t.down()
		t.right(85)
		t.forward(130)
		t.left(-140)
		t.circle(30,50)
		t.up()
		t.goto(-200,-90)
		t.down()
		t.left(80)
		t.circle(50,80)
		t.forward(50)	

		t.up()
		t.home()
		t.goto(-100,100)
		t.down()
		t.right(30)
		t.forward(30)
		t.up()
		t.goto(-90,110)
		t.down()
		t.forward(30)

		t.up()
		t.home()
		t.goto(-80,-60)
		t.down()

		t.left(30)
		t.circle(-100,40)
		t.right(5)
		t.circle(-15,150)
		t.up()
		t.goto(-70,-30)
		t.down()
		t.left(100)
		t.forward(60)
		t.up()
		t.goto(-20,-20)
		t.down()
		t.left(45)
		t.forward(20)

	def gyu(self):
		pygame.mixer.music.load("gyu.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('ぎゅ  ', font=style, align='center')		
	
		t.up()
		t.home()
		t.goto(-200,50)
		t.down()
		t.left(10)
		t.forward(100)
		t.up()
		t.goto(-210,0)
		t.down()
		t.forward(130)
		t.up()
		t.goto(-150,80)
		t.down()
		t.right(85)
		t.forward(130)
		t.left(-140)
		t.circle(30,50)
		t.up()
		t.goto(-200,-90)
		t.down()
		t.left(80)
		t.circle(50,80)
		t.forward(50)	

		t.up()
		t.home()
		t.goto(-100,100)
		t.down()
		t.right(30)
		t.forward(30)
		t.up()
		t.goto(-90,110)
		t.down()
		t.forward(30)

		t.up()
		t.home()
		t.goto(0,-50)
		t.down()

		t.right(100)
		t.forward(60)
		t.backward(20)
		t.left(150)
		t.circle(-60,20)
		t.circle(-40,70)
		t.right(10)
		t.circle(-20,50)
		t.circle(-40,75)
		t.forward(20)
		t.up()
		t.goto(30,-60)
		t.down()
		t.left(90)
		t.circle(-170,30)

	def gyo(self):
		pygame.mixer.music.load("gyo.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('ぎょ  ', font=style, align='center')		

		t.up()
		t.home()
		t.goto(-200,50)
		t.down()
		t.left(10)
		t.forward(100)
		t.up()
		t.goto(-210,0)
		t.down()
		t.forward(130)
		t.up()
		t.goto(-150,80)
		t.down()
		t.right(85)
		t.forward(130)
		t.left(-140)
		t.circle(30,50)
		t.up()
		t.goto(-200,-90)
		t.down()
		t.left(80)
		t.circle(50,80)
		t.forward(50)	

		t.up()
		t.home()
		t.goto(-100,100)
		t.down()
		t.right(30)
		t.forward(30)
		t.up()
		t.goto(-90,110)
		t.down()
		t.forward(30)

		t.up()
		t.home()
		t.goto(0,-50)
		t.down()

		t.forward(30)
		t.up()
		t.goto(0,-20)
		t.down()

		t.right(90)
		t.forward(90)
		t.circle(-15,270)
		t.circle(-70,50)

	def nya(self):
		pygame.mixer.music.load("nya.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('にゃ  ', font=style, align='center')		
	
		t.up()
		t.home()
		t.goto(-200,20)
		t.down()

		t.right(110)
		t.circle(250,35)
		t.left(150)
		t.circle(-30,30)

		t.up()
		t.goto(-170,-40)
		t.down()

		t.left(-30)
		t.circle(-150,30)

		t.up()
		t.goto(-170,-90)
		t.down()
		t.right(50)
		t.circle(30,70)
		t.forward(55)
		
		t.up()
		t.home()
		t.goto(-60,-60)
		t.down()

		t.left(30)
		t.circle(-100,40)
		t.right(5)
		t.circle(-15,150)
		t.up()
		t.goto(-50,-30)
		t.down()
		t.left(100)
		t.forward(60)
		t.up()
		t.goto(0,-20)
		t.down()
		t.left(45)
		t.forward(20)

	def nyu(self):
		pygame.mixer.music.load("nyu.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('にゅ  ', font=style, align='center')		
	
		t.up()
		t.home()
		t.goto(-200,20)
		t.down()

		t.right(110)
		t.circle(250,35)
		t.left(150)
		t.circle(-30,30)

		t.up()
		t.goto(-170,-40)
		t.down()

		t.left(-30)
		t.circle(-150,30)

		t.up()
		t.goto(-170,-90)
		t.down()
		t.right(50)
		t.circle(30,70)
		t.forward(55)

		t.up()
		t.home()
		t.goto(-20,-50)
		t.down()

		t.right(100)
		t.forward(60)
		t.backward(20)
		t.left(150)
		t.circle(-60,20)
		t.circle(-40,70)
		t.right(10)
		t.circle(-20,50)
		t.circle(-40,75)
		t.forward(20)
		t.up()
		t.goto(10,-60)
		t.down()
		t.left(90)
		t.circle(-170,30)

	def nyo(self):
		pygame.mixer.music.load("nyo.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('にょ  ', font=style, align='center')		
		
		t.up()
		t.home()
		t.goto(-200,20)
		t.down()

		t.right(110)
		t.circle(250,35)
		t.left(150)
		t.circle(-30,30)

		t.up()
		t.goto(-170,-40)
		t.down()

		t.left(-30)
		t.circle(-150,30)

		t.up()
		t.goto(-170,-90)
		t.down()
		t.right(50)
		t.circle(30,70)
		t.forward(55)

		t.up()
		t.home()
		t.goto(0,-50)
		t.down()

		t.forward(30)
		t.up()
		t.goto(0,-20)
		t.down()

		t.right(90)
		t.forward(90)
		t.circle(-15,270)
		t.circle(-70,50)

	def hya(self):
		pygame.mixer.music.load("hya.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('ひゃ  ', font=style, align='center')		
		
		t.up()
		t.home()
		t.goto(-200,-20)
		t.down()

		t.left(10)
		t.forward(70)
		t.right(135)
		t.circle(120,48)
		t.circle(60,130)
		t.right(-10)
		t.circle(100,60)
		t.right(160)
		t.forward(60)	

		t.up()
		t.home()
		t.goto(0,-120)
		t.down()

		t.left(30)
		t.circle(-100,40)
		t.right(5)
		t.circle(-15,150)
		t.up()
		t.goto(10,-90)
		t.down()
		t.left(100)
		t.forward(60)
		t.up()
		t.goto(60,-80)
		t.down()
		t.left(45)
		t.forward(20)

	def hyu(self):
		pygame.mixer.music.load("hyu.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('ひゅ  ', font=style, align='center')		
		
		t.up()
		t.home()
		t.goto(-200,-20)
		t.down()

		t.left(10)
		t.forward(70)
		t.right(135)
		t.circle(120,48)
		t.circle(60,130)
		t.right(-10)
		t.circle(100,60)
		t.right(160)
		t.forward(60)	

		t.up()
		t.home()
		t.goto(20,-50)
		t.down()

		t.right(100)
		t.forward(60)
		t.backward(20)
		t.left(150)
		t.circle(-60,20)
		t.circle(-40,70)
		t.right(10)
		t.circle(-20,50)
		t.circle(-40,75)
		t.forward(20)
		t.up()
		t.goto(50,-60)
		t.down()
		t.left(90)
		t.circle(-170,30)

	def hyo(self):
		pygame.mixer.music.load("hyo.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('ひょ  ', font=style, align='center')	
		
		t.up()
		t.home()
		t.goto(-200,-20)
		t.down()

		t.left(10)
		t.forward(70)
		t.right(135)
		t.circle(120,48)
		t.circle(60,130)
		t.right(-10)
		t.circle(100,60)
		t.right(160)
		t.forward(60)	

		t.up()
		t.home()
		t.goto(30,-80)
		t.down()

		t.forward(30)
		t.up()
		t.goto(30,-50)
		t.down()

		t.right(90)
		t.forward(90)
		t.circle(-15,270)
		t.circle(-70,50)

	def bya(self):
		pygame.mixer.music.load("bya.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('びゃ  ', font=style, align='center')	
		
		t.up()
		t.home()
		t.goto(-200,-20)
		t.down()

		t.left(10)
		t.forward(70)
		t.right(135)
		t.circle(120,48)
		t.circle(60,130)
		t.right(-10)
		t.circle(100,60)
		t.right(160)
		t.forward(60)	

		t.up()
		t.home()
		t.goto(-40,-10)
		t.down()
		t.right(30)
		t.forward(25)
		t.up()
		t.goto(-30,0)
		t.down()
		t.forward(25)

		t.up()
		t.home()
		t.goto(0,-120)
		t.down()

		t.left(30)
		t.circle(-100,40)
		t.right(5)
		t.circle(-15,150)
		t.up()
		t.goto(10,-90)
		t.down()
		t.left(100)
		t.forward(60)
		t.up()
		t.goto(60,-80)
		t.down()
		t.left(45)
		t.forward(20)

	def byu(self):
		pygame.mixer.music.load("byu.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('びゅ  ', font=style, align='center')		
		
		t.up()
		t.home()
		t.goto(-200,-20)
		t.down()

		t.left(10)
		t.forward(70)
		t.right(135)
		t.circle(120,48)
		t.circle(60,130)
		t.right(-10)
		t.circle(100,60)
		t.right(160)
		t.forward(60)

		t.up()
		t.home()
		t.goto(-40,-10)
		t.down()
		t.right(30)
		t.forward(25)
		t.up()
		t.goto(-30,0)
		t.down()
		t.forward(25)	

		t.up()
		t.home()
		t.goto(20,-50)
		t.down()

		t.right(100)
		t.forward(60)
		t.backward(20)
		t.left(150)
		t.circle(-60,20)
		t.circle(-40,70)
		t.right(10)
		t.circle(-20,50)
		t.circle(-40,75)
		t.forward(20)
		t.up()
		t.goto(50,-60)
		t.down()
		t.left(90)
		t.circle(-170,30)

	def byo(self):
		pygame.mixer.music.load("byo.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('びょ  ', font=style, align='center')		
		
		t.up()
		t.home()
		t.goto(-200,-20)
		t.down()

		t.left(10)
		t.forward(70)
		t.right(135)
		t.circle(120,48)
		t.circle(60,130)
		t.right(-10)
		t.circle(100,60)
		t.right(160)
		t.forward(60)

		t.up()
		t.home()
		t.goto(-40,-10)
		t.down()
		t.right(30)
		t.forward(25)
		t.up()
		t.goto(-30,0)
		t.down()
		t.forward(25)	

		t.up()
		t.home()
		t.goto(30,-80)
		t.down()

		t.forward(30)
		t.up()
		t.goto(30,-50)
		t.down()

		t.right(90)
		t.forward(90)
		t.circle(-15,270)
		t.circle(-70,50)

	def pya(self):
		pygame.mixer.music.load("pya.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('ぴゃ  ', font=style, align='center')		
	
		t.up()
		t.home()
		t.goto(-200,-20)
		t.down()

		t.left(10)
		t.forward(70)
		t.right(135)
		t.circle(120,48)
		t.circle(60,130)
		t.right(-10)
		t.circle(100,60)
		t.right(160)
		t.forward(60)

		t.up()
		t.goto(-20,-20)
		t.down()

		t.left(10)
		t.pensize(5)
		t.circle(15)
		t.pensize(5)		

		t.up()
		t.home()
		t.goto(0,-120)
		t.down()

		t.left(30)
		t.circle(-100,40)
		t.right(5)
		t.circle(-15,150)
		t.up()
		t.goto(10,-90)
		t.down()
		t.left(100)
		t.forward(60)
		t.up()
		t.goto(60,-80)
		t.down()
		t.left(45)
		t.forward(20)

	def pyu(self):
		pygame.mixer.music.load("pyu.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('ぴゅ  ', font=style, align='center')		
	
		t.up()
		t.home()
		t.goto(-200,-20)
		t.down()

		t.left(10)
		t.forward(70)
		t.right(135)
		t.circle(120,48)
		t.circle(60,130)
		t.right(-10)
		t.circle(100,60)
		t.right(160)
		t.forward(60)	

		t.up()
		t.goto(-20,-20)
		t.down()

		t.left(10)
		t.pensize(5)
		t.circle(15)
		t.pensize(5)

		t.up()
		t.home()
		t.goto(20,-50)
		t.down()

		t.right(100)
		t.forward(60)
		t.backward(20)
		t.left(150)
		t.circle(-60,20)
		t.circle(-40,70)
		t.right(10)
		t.circle(-20,50)
		t.circle(-40,75)
		t.forward(20)
		t.up()
		t.goto(50,-60)
		t.down()
		t.left(90)
		t.circle(-170,30)

	def pyo(self):
		pygame.mixer.music.load("pyo.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('ぴょ  ', font=style, align='center')		
		
		t.up()
		t.home()
		t.goto(-200,-20)
		t.down()

		t.left(10)
		t.forward(70)
		t.right(135)
		t.circle(120,48)
		t.circle(60,130)
		t.right(-10)
		t.circle(100,60)
		t.right(160)
		t.forward(60)	

		t.up()
		t.goto(-20,-20)
		t.down()

		t.left(10)
		t.pensize(5)
		t.circle(15)
		t.pensize(5)

		t.up()
		t.home()
		t.goto(30,-80)
		t.down()

		t.forward(30)
		t.up()
		t.goto(30,-50)
		t.down()

		t.right(90)
		t.forward(90)
		t.circle(-15,270)
		t.circle(-70,50)

	def mya(self):
		pygame.mixer.music.load("mya.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('みゃ  ', font=style, align='center')		
		
		t.up()
		t.home()
		t.goto(-200,0)
		t.down()

		t.forward(60)
		t.right(115)
		t.forward(100)
		t.circle(-30,80)
		t.right(50)
		t.circle(-30,105)
		t.left(10)
		t.circle(-100,70)

		t.up()
		t.goto(-100,-30)
		t.down()
		t.right(40)
		t.circle(-150,45)

		t.up()
		t.home()
		t.goto(-70,-100)
		t.down()

		t.left(30)
		t.circle(-100,40)
		t.right(5)
		t.circle(-15,150)
		t.up()
		t.goto(-60,-70)
		t.down()
		t.left(100)
		t.forward(60)
		t.up()
		t.goto(-20,-60)
		t.down()
		t.left(45)
		t.forward(20)

	def myu(self):
		pygame.mixer.music.load("myu.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('みゅ  ', font=style, align='center')		
		
		t.up()
		t.home()
		t.goto(-200,0)
		t.down()

		t.forward(60)
		t.right(115)
		t.forward(100)
		t.circle(-30,80)
		t.right(50)
		t.circle(-30,105)
		t.left(10)
		t.circle(-100,70)

		t.up()
		t.goto(-100,-30)
		t.down()
		t.right(40)
		t.circle(-150,45)

		t.up()
		t.home()
		t.goto(-30,-50)
		t.down()

		t.right(100)
		t.forward(60)
		t.backward(20)
		t.left(150)
		t.circle(-60,20)
		t.circle(-40,70)
		t.right(10)
		t.circle(-20,50)
		t.circle(-40,75)
		t.forward(20)
		t.up()
		t.goto(0,-60)
		t.down()
		t.left(90)
		t.circle(-170,30)

	def myo(self):
		pygame.mixer.music.load("myo.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('みょ  ', font=style, align='center')	

		t.up()
		t.home()
		t.goto(-200,0)
		t.down()

		t.forward(60)
		t.right(115)
		t.forward(100)
		t.circle(-30,80)
		t.right(50)
		t.circle(-30,105)
		t.left(10)
		t.circle(-100,70)

		t.up()
		t.goto(-100,-30)
		t.down()
		t.right(40)
		t.circle(-150,45)

		t.up()
		t.home()
		t.goto(-30,-70)
		t.down()

		t.forward(30)
		t.up()
		t.goto(-30,-40)
		t.down()

		t.right(90)
		t.forward(90)
		t.circle(-15,270)
		t.circle(-70,50)

	def rya(self):
		pygame.mixer.music.load("rya.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('りゃ  ', font=style, align='center')		

		t.up()
		t.home()
		t.goto(-200,0)
		t.down()

		t.right(100)
		t.circle(250,18)
		t.left(150)
		t.circle(-50,30)

		t.up()
		t.goto(-120,0)
		t.down()
		t.right(110)
		t.circle(-100,20)
		t.circle(-200,40)

		t.up()
		t.home()
		t.goto(-80,-90)
		t.down()

		t.left(30)
		t.circle(-100,40)
		t.right(5)
		t.circle(-15,150)
		t.up()
		t.goto(-70,-60)
		t.down()
		t.left(100)
		t.forward(60)
		t.up()
		t.goto(-20,-50)
		t.down()
		t.left(45)
		t.forward(20)

	def ryu(self):
		pygame.mixer.music.load("ryu.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('りゅ  ', font=style, align='center')		
	
		t.up()
		t.home()
		t.goto(-200,0)
		t.down()

		t.right(100)
		t.circle(250,18)
		t.left(150)
		t.circle(-50,30)

		t.up()
		t.goto(-120,0)
		t.down()
		t.right(110)
		t.circle(-100,20)
		t.circle(-200,40)

		t.up()
		t.home()
		t.goto(-50,-50)
		t.down()

		t.right(100)
		t.forward(60)
		t.backward(20)
		t.left(150)
		t.circle(-60,20)
		t.circle(-40,70)
		t.right(10)
		t.circle(-20,50)
		t.circle(-40,75)
		t.forward(20)
		t.up()
		t.goto(-20,-60)
		t.down()
		t.left(90)
		t.circle(-170,30)

	def ryo(self):
		pygame.mixer.music.load("ryo.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('りょ  ', font=style, align='center')		

		t.up()
		t.home()
		t.goto(-200,0)
		t.down()

		t.right(100)
		t.circle(250,18)
		t.left(150)
		t.circle(-50,30)

		t.up()
		t.goto(-120,0)
		t.down()
		t.right(110)
		t.circle(-100,20)
		t.circle(-200,40)

		t.speed(5)
		t.up()
		t.home()
		t.goto(-50,-70)
		t.down()

		t.forward(30)
		t.up()
		t.goto(-50,-40)
		t.down()

		t.right(90)
		t.forward(90)
		t.circle(-15,270)
		t.circle(-70,50)

	def ja(self):
		pygame.mixer.music.load("ja.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('じゃ  ', font=style, align='center')		
		
		t.up()
		t.home()
		t.goto(-150,0)
		t.down()

		t.right(110)
		t.circle(200,30)
		t.circle(30,100)
		t.left(3)
		t.forward(30)

		t.up()
		t.home()
		t.goto(-130,-10)
		t.down()
		t.right(30)
		t.forward(30)
		t.up()
		t.goto(-120,00)
		t.down()
		t.forward(30)

		t.up()
		t.home()
		t.goto(-80,-80)
		t.down()

		t.left(30)
		t.circle(-100,40)
		t.right(5)
		t.circle(-15,150)
		t.up()
		t.goto(-70,-50)
		t.down()
		t.left(100)
		t.forward(60)
		t.up()
		t.goto(-20,-50)
		t.down()
		t.left(45)
		t.forward(20)

	def ju(self):
		pygame.mixer.music.load("ju.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('じゅ  ', font=style, align='center')		
		
		t.up()
		t.home()
		t.goto(-150,0)
		t.down()

		t.right(110)
		t.circle(200,30)
		t.circle(30,100)
		t.left(3)
		t.forward(30)

		t.up()
		t.home()
		t.goto(-130,-10)
		t.down()
		t.right(30)
		t.forward(30)
		t.up()
		t.goto(-120,00)
		t.down()
		t.forward(30)

		t.up()
		t.home()
		t.goto(-20,-50)
		t.down()

		t.right(100)
		t.forward(60)
		t.backward(20)
		t.left(150)
		t.circle(-60,20)
		t.circle(-40,70)
		t.right(10)
		t.circle(-20,50)
		t.circle(-40,75)
		t.forward(20)
		t.up()
		t.goto(10,-60)
		t.down()
		t.left(90)
		t.circle(-170,30)

	def jo(self):
		pygame.mixer.music.load("jo.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('じょ  ', font=style, align='center')		
		
		t.up()
		t.home()
		t.goto(-150,0)
		t.down()

		t.right(110)
		t.circle(200,30)
		t.circle(30,100)
		t.left(3)
		t.forward(30)

		t.up()
		t.home()
		t.goto(-130,-10)
		t.down()
		t.right(30)
		t.forward(30)
		t.up()
		t.goto(-120,00)
		t.down()
		t.forward(30)

		t.up()
		t.home()
		t.goto(-10,-50)
		t.down()

		t.forward(30)
		t.up()
		t.goto(-10,-20)
		t.down()

		t.right(90)
		t.forward(90)
		t.circle(-15,270)
		t.circle(-70,50)

	def cha(self):
		pygame.mixer.music.load("cha.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('ちゃ  ', font=style, align='center')		
		
		t.up()
		t.home()
		t.goto(-200,20)
		t.down()

		t.forward(100)

		t.up()
		t.goto(-130,50)
		t.down()

		t.right(120)
		t.forward(100)
		t.left(140)
		t.circle(-50,200)
		t.forward(50)

		t.up()
		t.home()
		t.goto(-80,-80)
		t.down()

		t.left(30)
		t.circle(-100,40)
		t.right(5)
		t.circle(-15,150)
		t.up()
		t.goto(-70,-50)
		t.down()
		t.left(100)
		t.forward(60)
		t.up()
		t.goto(-20,-50)
		t.down()
		t.left(45)
		t.forward(20)

	def chu(self):
		pygame.mixer.music.load("chu.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('ちゅ  ', font=style, align='center')	

		t.up()
		t.home()
		t.goto(-200,20)
		t.down()

		t.forward(100)

		t.up()
		t.goto(-130,50)
		t.down()

		t.right(120)
		t.forward(100)
		t.left(140)
		t.circle(-50,200)
		t.forward(50)

		t.up()
		t.home()
		t.goto(-30,-50)
		t.down()

		t.right(100)
		t.forward(60)
		t.backward(20)
		t.left(150)
		t.circle(-60,20)
		t.circle(-40,70)
		t.right(10)
		t.circle(-20,50)
		t.circle(-40,75)
		t.forward(20)
		t.up()
		t.goto(0,-60)
		t.down()
		t.left(90)
		t.circle(-170,30)
		
	def cho(self):
		pygame.mixer.music.load("cho.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('ちょ  ', font=style, align='center')		
		
		t.up()
		t.home()
		t.goto(-200,20)
		t.down()

		t.forward(100)

		t.up()
		t.goto(-130,50)
		t.down()

		t.right(120)
		t.forward(100)
		t.left(140)
		t.circle(-50,200)
		t.forward(50)

		t.up()
		t.home()
		t.goto(-20,-50)
		t.down()

		t.forward(30)
		t.up()
		t.goto(-20,-20)
		t.down()

		t.right(90)
		t.forward(90)
		t.circle(-15,270)
		t.circle(-70,50)

	def sha(self):
		pygame.mixer.music.load("sha.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('しゃ  ', font=style, align='center')	
		
		t.up()
		t.home()
		t.goto(-160,0)
		t.down()

		t.right(110)
		t.circle(200,30)
		t.circle(30,100)
		t.left(3)
		t.forward(30)

		t.up()
		t.home()
		t.goto(-80,-60)
		t.down()

		t.left(30)
		t.circle(-100,40)
		t.right(5)
		t.circle(-15,150)
		t.up()
		t.goto(-70,-30)
		t.down()
		t.left(100)
		t.forward(60)
		t.up()
		t.goto(-20,-20)
		t.down()
		t.left(45)
		t.forward(20)

	def shu(self):
		pygame.mixer.music.load("shu.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('しゅ  ', font=style, align='center')	
		
		t.up()
		t.home()
		t.goto(-160,0)
		t.down()

		t.right(110)
		t.circle(200,30)
		t.circle(30,100)
		t.left(3)
		t.forward(30)

		t.up()
		t.home()
		t.goto(-30,-50)
		t.down()

		t.right(100)
		t.forward(60)
		t.backward(20)
		t.left(150)
		t.circle(-60,20)
		t.circle(-40,70)
		t.right(10)
		t.circle(-20,50)
		t.circle(-40,75)
		t.forward(20)
		t.up()
		t.goto(0,-60)
		t.down()
		t.left(90)
		t.circle(-170,30)
		
	def sho(self):
		pygame.mixer.music.load("sho.mpeg")
		pygame.mixer.music.play(loops=0)
		t.hideturtle()
		t.clear()
		t.up()
		t.goto(-150,150)
		t.down()
		style = ('Courier', 40, 'italic')
		t.write('しょ  ', font=style, align='center')		
		
		t.up()
		t.home()
		t.goto(-160,0)
		t.down()

		t.right(110)
		t.circle(200,30)
		t.circle(30,100)
		t.left(3)
		t.forward(30)

		t.up()
		t.home()
		t.goto(-30,-50)
		t.down()

		t.forward(30)
		t.up()
		t.goto(-30,-20)
		t.down()

		t.right(90)
		t.forward(90)
		t.circle(-15,270)
		t.circle(-70,50)

con=hiragana()


canvas = Canvas(root, width=500, height=550)
canvas.grid(row=1, column=21,rowspan=35, columnspan=1, pady=40, padx=10)

EtoJ=ttk.Label(root, text=" TRANSLATE IN JAPANESE LANGUAGE ",background="pink",foreground='#1E90FF',font='tahoma 20 bold')
EtoJ.grid(row=1, column=21, columnspan=5)

t = turtle.RawTurtle(canvas)
t.pencolor("#1E90FF")
t.shapesize(1)
t.pensize(5)
t.speed(5)
		
ft = 'tahoma 11 bold'
btn_style = ttk.Style()
btn_style.configure('TButton', background="green", forground="blue",  height=10, width=4, font=ft) 
                                    
a = ttk.Button(root, text='a', style='TButton', command=con.a)
i = ttk.Button(root, text='i', style='TButton', command=con.i)
u = ttk.Button(root, text='u', style='TButton', command=con.u)
e = ttk.Button(root, text='e', style='TButton', command=con.e)
o=ttk.Button(root,text='o', style='TButton', command=con.o)

ka = ttk.Button(root, text='ka', style='TButton', command=con.ka)
ki = ttk.Button(root, text='ki', style='TButton', command=con.ki)
ku = ttk.Button(root, text='ku', style='TButton', command=con.ku)
k_e = ttk.Button(root, text='ke', style='TButton', command=con.ke)
k_o = ttk.Button(root,text='ko', style='TButton', command=con.ko)

ga = ttk.Button(root, text='ga', style='TButton', command=con.ga)
gi = ttk.Button(root, text='gi', style='TButton', command=con.gi)
gu = ttk.Button(root, text='gu', style='TButton', command=con.gu)
ge = ttk.Button(root, text='ge', style='TButton', command=con.ge)
go=ttk.Button(root,text='go', style='TButton', command=con.go)

sa = ttk.Button(root, text='sa', style='TButton', command=con.sa)
shi = ttk.Button(root, text='shi', style='TButton', command=con.shi)
su = ttk.Button(root, text='su', style='TButton', command=con.su)
se = ttk.Button(root, text='se', style='TButton', command=con.se)
so=ttk.Button(root,text='so', style='TButton', command=con.so)

za = ttk.Button(root, text='za', style='TButton', command=con.za)
ji_zi = ttk.Button(root, text='ji', style='TButton', command=con.ji_zi)
zu_zu = ttk.Button(root, text='zu', style='TButton', command=con.zu_zu)
ze = ttk.Button(root, text='ze', style='TButton', command=con.ze)
zo=ttk.Button(root,text='zo', style='TButton', command=con.zo)

ta = ttk.Button(root, text='ta', style='TButton', command=con.ta)
chi = ttk.Button(root, text='chi', style='TButton', command=con.chi)
tsu = ttk.Button(root, text='tsu', style='TButton', command=con.tsu)
te = ttk.Button(root, text='te', style='TButton', command=con.te)
to=ttk.Button(root,text='to', style='TButton', command=con.to)

da = ttk.Button(root, text='da', style='TButton', command=con.da)
ji = ttk.Button(root, text='ji', style='TButton', command=con.ji)
zu = ttk.Button(root, text='zu', style='TButton', command=con.zu)
de = ttk.Button(root, text='de', style='TButton', command=con.de)
do=ttk.Button(root,text='do', style='TButton', command=con.do)

na = ttk.Button(root, text='na', style='TButton', command=con.na)
ni = ttk.Button(root, text='ni', style='TButton', command=con.ni)
nu = ttk.Button(root, text='nu', style='TButton', command=con.nu)
ne = ttk.Button(root, text='ne', style='TButton', command=con.ne)
no=ttk.Button(root,text='no', style='TButton', command=con.no)

ha = ttk.Button(root, text='ha', style='TButton', command=con.ha)
hi = ttk.Button(root, text='hi', style='TButton', command=con.hi)
fu = ttk.Button(root, text='fu', style='TButton', command=con.fu)
he = ttk.Button(root, text='he', style='TButton', command=con.he)
ho=ttk.Button(root,text='ho', style='TButton', command=con.ho)

ba = ttk.Button(root, text='ba', style='TButton', command=con.ba)
bi = ttk.Button(root, text='bi', style='TButton', command=con.bi)
bu = ttk.Button(root, text='bu', style='TButton', command=con.bu)
be = ttk.Button(root, text='be', style='TButton', command=con.be)
bo=ttk.Button(root,text='bo', style='TButton', command=con.bo)

pa = ttk.Button(root, text='pa', style='TButton', command=con.pa)
pi = ttk.Button(root, text='pi', style='TButton', command=con.pi)
pu = ttk.Button(root, text='pu', style='TButton', command=con.pu)
pe = ttk.Button(root, text='pe', style='TButton', command=con.pe)
po=ttk.Button(root,text='po', style='TButton', command=con.po)

ma = ttk.Button(root, text='ma', style='TButton', command=con.ma)
mi = ttk.Button(root, text='mi', style='TButton', command=con.mi)
mu = ttk.Button(root, text='mu', style='TButton', command=con.mu)
me = ttk.Button(root, text='me', style='TButton', command=con.me)
mo=ttk.Button(root,text='mo', style='TButton', command=con.mo)

ya = ttk.Button(root, text='ya', style='TButton', command=con.ya)
yu = ttk.Button(root, text='yu', style='TButton', command=con.yu)
yo = ttk.Button(root, text='yo', style='TButton', command=con.yo)

ra = ttk.Button(root, text='ra', style='TButton', command=con.ra)
ri = ttk.Button(root, text='ri', style='TButton', command=con.ri)
ru = ttk.Button(root, text='ru', style='TButton', command=con.ru)
re = ttk.Button(root, text='re', style='TButton', command=con.re)
ro=ttk.Button(root,text='ro', style='TButton', command=con.ro)

wa = ttk.Button(root, text='wa', style='TButton', command=con.wa)
wo = ttk.Button(root, text='wo', style='TButton', command=con.wo)
n=ttk.Button(root,text='n', style='TButton', command=con.n)

kya = ttk.Button(root, text='kya', style='TButton', command=con.kya)
kyu = ttk.Button(root, text='kyu', style='TButton', command=con.kyu)
kyo = ttk.Button(root, text='kyo', style='TButton', command=con.kyo)

gya = ttk.Button(root, text='gya', style='TButton', command=con.gya)
gyu=ttk.Button(root,text='gyu', style='TButton', command=con.gyu)
gyo = ttk.Button(root, text='gyo', style='TButton', command=con.gyo)

nya = ttk.Button(root, text='nya', style='TButton', command=con.nya)
nyu = ttk.Button(root, text='nyu', style='TButton', command=con.nyu)
nyo = ttk.Button(root, text='nyo', style='TButton', command=con.nyo)

hya=ttk.Button(root,text='hya', style='TButton', command=con.hya)
hyu = ttk.Button(root, text='hyu', style='TButton', command=con.hyu)
hyo = ttk.Button(root, text='hyo', style='TButton', command=con.hyo)

bya = ttk.Button(root, text='bya', style='TButton', command=con.bya)
byu = ttk.Button(root, text='byu', style='TButton', command=con.byu)
byo=ttk.Button(root,text='byo', style='TButton', command=con.byo)

pya = ttk.Button(root, text='pya', style='TButton', command=con.pya)
pyu = ttk.Button(root, text='pyu', style='TButton', command=con.pyu)
pyo = ttk.Button(root, text='pyo', style='TButton', command=con.pyo)

mya = ttk.Button(root, text='mya', style='TButton', command=con.mya)
myu=ttk.Button(root,text='myu', style='TButton', command=con.myu)
myo = ttk.Button(root, text='myo', style='TButton', command=con.myo)

rya = ttk.Button(root, text='rya', style='TButton', command=con.rya)
ryu = ttk.Button(root, text='ryu', style='TButton', command=con.ryu)
ryo = ttk.Button(root, text='ryo', style='TButton', command=con.ryo)

ja=ttk.Button(root,text='ja', style='TButton', command=con.ja)
ju = ttk.Button(root, text='ju', style='TButton', command=con.ju)
jo = ttk.Button(root, text='jo', style='TButton', command=con.jo)

cha = ttk.Button(root, text='cha', style='TButton', command=con.cha)
chu = ttk.Button(root, text='chu', style='TButton', command=con.chu)
cho = ttk.Button(root, text='cho', style='TButton', command=con.cho)

sha=ttk.Button(root,text='sha', style='TButton', command=con.sha)
shu = ttk.Button(root, text='shu', style='TButton', command=con.shu)
sho=ttk.Button(root,text='sho', style='TButton', command=con.sho)

hira=ttk.Label(root, text="HIRAGANA",background="pink",foreground='#1E90FF', font=ft)
hira.grid(row=1, column=2, columnspan=5)

additional=ttk.Label(root, text="ADDITIONAL SOUND", background="pink",foreground='#1E90FF', font=ft)
additional.grid(row=1, column=9, columnspan=6)

a.grid(row=2, column=1, pady=10,padx=10)
i.grid(row=2, column=2, pady=10,padx=10)
u.grid(row=2, column=3,pady=10, padx=10)
e.grid(row=2, column=4,pady=10,padx=10)
o.grid(row=2,column=5,pady=10, padx=10) 

ka.grid(row=3, column=1, pady=10,padx=10)
ki.grid(row=3, column=2, pady=10,padx=10)
ku.grid(row=3, column=3, pady=10, padx=10)
k_e.grid(row=3, column=4, pady=10,padx=10)
k_o.grid(row=3, column=5, pady=10, padx=10, columnspan=2)

sa.grid(row=4, column=1, pady=10,padx=1)
shi.grid(row=4, column=2, pady=10,padx=1)
su.grid(row=4, column=3,pady=10, padx=1)
se.grid(row=4, column=4,pady=10,padx=1)
so.grid(row=4, column=5,pady=10, padx=1) 

ta.grid(row=5, column=1, pady=10,padx=1)
chi.grid(row=5, column=2, pady=10,padx=1)
tsu.grid(row=5, column=3,pady=10, padx=1)
te.grid(row=5, column=4,pady=10,padx=1)
to.grid(row=5,column=5,pady=10,padx=1)    

na.grid(row=6, column=1, pady=10, padx=1)
ni.grid(row=6, column=2, pady=10,padx=1)
nu.grid(row=6, column=3,pady=10, padx=1)
ne.grid(row=6, column=4,pady=10,padx=1)
no.grid(row=6,column=5,pady=10, padx=1) 

ha.grid(row=7, column=1, pady=10,padx=1)
hi.grid(row=7, column=2, pady=10,padx=1)
fu.grid(row=7, column=3,pady=10, padx=1)
he.grid(row=7, column=4,pady=10,padx=1)
ho.grid(row=7,column=5,pady=10, padx=1)

ma.grid(row=8, column=1, pady=10,padx=1)
mi.grid(row=8, column=2, pady=10,padx=1)
mu.grid(row=8, column=3,pady=10, padx=1)
me.grid(row=8, column=4,pady=10,padx=1)
mo.grid(row=8, column=5,pady=10, padx=1) 

ya.grid(row=9, column=1, pady=10,padx=1)
yu.grid(row=9, column=3, pady=10,padx=1)
yo.grid(row=9, column=5,pady=10, padx=1)

ra.grid(row=10, column=1, pady=10,padx=1)
ri.grid(row=10, column=2, pady=10,padx=1)
ru.grid(row=10, column=3,pady=10, padx=1)
re.grid(row=10, column=4,pady=10,padx=1)
ro.grid(row=10,column=5,pady=10, padx=1)                                                      

wa.grid(row=11, column=1, pady=10,padx=1)
wo.grid(row=11, column=5, pady=10,padx=1)
n.grid(row=12, column=1,pady=10, padx=1)  

ga.grid(row=2, column=9, pady=10,padx=1)
gi.grid(row=2, column=10, pady=10,padx=1)
gu.grid(row=2, column=11,pady=10, padx=1)
ge.grid(row=2, column=12,pady=10,padx=1)
go.grid(row=2,column=13,pady=10, padx=1) 

za.grid(row=3, column=9, pady=10,padx=1)
ji_zi.grid(row=3, column=10, pady=10,padx=1)
zu_zu.grid(row=3, column=11, pady=10, padx=1)
ze.grid(row=3, column=12, pady=10,padx=1)
zo.grid(row=3,column=13, pady=10, padx=1)

da.grid(row=4, column=9, pady=10,padx=1)
ji.grid(row=4, column=10, pady=10,padx=1)
zu.grid(row=4, column=11,pady=10, padx=1)
de.grid(row=4, column=12,pady=10,padx=1)
do.grid(row=4, column=13,pady=10, padx=1) 

ba.grid(row=5, column=9, pady=10,padx=1)
bi.grid(row=5, column=10, pady=10,padx=1)
bu.grid(row=5, column=11,pady=10, padx=1)
be.grid(row=5, column=12,pady=10,padx=1)
bo.grid(row=5,column=13,pady=10,padx=10)    

pa.grid(row=6, column=9, pady=10, padx=10)
pi.grid(row=6, column=10, pady=10,padx=1)
pu.grid(row=6, column=11,pady=10, padx=10)
pe.grid(row=6, column=12,pady=10,padx=10)
po.grid(row=6,column=13,pady=10, padx=10) 

kya.grid(row=7, column=9, pady=10,padx=1)
kyu.grid(row=7, column=10, pady=10,padx=1)
kyo.grid(row=7, column=11,pady=10, padx=1)

gya.grid(row=7, column=12,pady=10,padx=1)
gyu.grid(row=7,column=13,pady=10, padx=1) 
gyo.grid(row=7, column=14, pady=10,padx=1)

nya.grid(row=8, column=9, pady=10,padx=1)
nyu.grid(row=8, column=10, pady=10, padx=1)
nyo.grid(row=8, column=11, pady=10,padx=1)

hya.grid(row=8,column=12, pady=10, padx=1)
hyu.grid(row=8, column=13, pady=10,padx=1)
hyo.grid(row=8, column=14, pady=10,padx=1)

bya.grid(row=9, column=9,pady=10, padx=1)
byu.grid(row=9, column=10,pady=10,padx=1)
byo.grid(row=9, column=11,pady=10, padx=1) 

pya.grid(row=9, column=12, pady=10,padx=1)
pyu.grid(row=9, column=13, pady=10,padx=1)
pyo.grid(row=9, column=14,pady=10, padx=1)

mya.grid(row=10, column=9,pady=10,padx=1)
myu.grid(row=10,column=10,pady=10,padx=10)    
myo.grid(row=10, column=11, pady=10, padx=10)

rya.grid(row=10, column=12, pady=10,padx=1)
ryu.grid(row=10, column=13,pady=10, padx=10)
ryo.grid(row=10, column=14,pady=10,padx=10)

ja.grid(row=11,column=9,pady=10, padx=10)
ju.grid(row=11, column=10,pady=10,padx=1)
jo.grid(row=11, column=11, pady=10,padx=1)

cha.grid(row=11, column=12, pady=10,padx=1)
chu.grid(row=11, column=13,pady=10, padx=1)
cho.grid(row=11,column=14,pady=10,padx=10)   
 
sha.grid(row=12, column=9, pady=10, padx=10)
shu.grid(row=12, column=10, pady=10,padx=1)
sho.grid(row=12, column=11, pady=10,padx=10) 

lbl1 = Label(root, text='|')
lbl2 = Label(root, text='|')
lbl3 = Label(root, text='|')
lbl4 = Label(root, text='|')

ft2 = 'impact 13 bold'
lbl1.config(bg='white', fg='pink', font=ft2)
lbl2.config(bg='white', fg='pink', font=ft2)
lbl3.config(bg='white', fg='pink', font=ft2)
lbl4.config(bg='white', fg='pink', font=ft2)

lbl1.grid(row=2, column=8, pady=10, padx=20)
lbl2.grid(row=5, column=8, pady=10, padx=20)
lbl3.grid(row=8, column=8, pady=10, padx=20)
lbl4.grid(row=11, column=8, pady=10, padx=20)


exit_btn = Button(root, text='Exit', command=con.exit)
exit_btn.config(bg='#1E90FF', fg='WHITE', font='tahoma 13 bold' )
exit_btn.grid(row=14, column=3,ipadx=0, ipady=0, padx=5, pady=5, columnspan=9)
                                  
root.resizable(False,False)                    
root.mainloop()